analyzer:
  exclude:
    - lib/**.g.dart
    - test/**.mocks.dart
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    unrelated_type_equality_checks: error
    missing_return: warning
    parameter_assignments: warning
    prefer_final_in_for_each: warning
    prefer_mixin: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_null_aware_assignments: warning
    use_string_buffers: warning
    use_if_null_to_convert_nulls_to_bools: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - constant_identifier_names
    - exhaustive_cases
    - parameter_assignments
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_to_and_as_if_applicable
    - prefer_relative_imports
    - avoid_unused_constructor_parameters
    - directives_ordering
    - unnecessary_statements
    - avoid_annotating_with_dynamic
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_string_buffers
    - non_constant_identifier_names
    - prefer_const_constructors
    - empty_statements
    - prefer_void_to_null
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - empty_constructor_bodies
    - implementation_imports
    - no_leading_underscores_for_local_identifiers
    - null_closures
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
