name: aoc
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  characters: ^1.2.1
  collection: ^1.17.0
  equatable: ^2.0.5
  html: ^0.15.1
  http: ^0.13.5
  meta: ^1.8.0
  quiver: ^3.1.0
  tuple: ^2.0.1

dev_dependencies:
  test: ^1.22.0
